---
- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Create users
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    state: present
    generate_ssh_key: yes
    ssh_key_file: "/home/{{ item }}/.ssh/id_rsa"
    createhome: yes
  loop:
    - user100
    - user200
    - user300

- name: Download user100 private key
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "/tmp/private_keys/user100_id_rsa"
    flat: yes
