---
- name: Ensure the necessary Python packages are installed
  yum:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install Apache
  yum:
    name: httpd
    state: present
  become: yes

- name: Start and enable Apache service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes

- name: Create index.html file
  copy:
    content: "{{ inventory_hostname }}"
    dest: /var/www/html/index.html
    mode: '0444'
  become: yes
