---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-n01654966
    - profile-n01654966
    - user-n01654966
    - webserver-n01654966

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"